CREATE TABLE customers (
    id SERIAL PRIMARY KEY,
    name VARCHAR(40) NOT NULL,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    "createAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE sessions (
    id SERIAL PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    "customerId" INTEGER NOT NULL UNIQUE REFERENCES "customers"("id"),
    "createAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE urls (
    id SERIAL PRIMARY KEY,
    "shortUrl" VARCHAR(9) NOT NULL UNIQUE,
    url TEXT NOT NULL,
    "customerId" INTEGER NOT NULL REFERENCES "customers"("id"),
    "visitCount" INTEGER DEFAULT (0) NOT NULL,
    "createAt" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    UNIQUE ("customerId", url)
);